name: federated-systems

services:
  static-page:
    build:
      dockerfile: Dockerfile
      context: clients/static-page
    ports:
      - 9090:80

  weather-api:
    build:
      dockerfile: Dockerfile
      context: backends/weather-api
    ports:
      - 8080:8080
