import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {FaGithubSquare} from 'react-icons/fa'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[inter.className, "grid grid-rows-[minmax(1em,auto)_1fr_minmax(1em,auto)] min-h-screen"].join(" ")}>
        <header className="flex justify-between px-2 py-1 bg-rose-950 text-amber-50">
          <p>Logo</p>

          <nav>
            <ul className="flex gap-4">
              {[
                  {href: "/", title: "Home"},
                  {href: "/about", title: "About"},
                ].map(link => (
                  <li className="hover:scale-105" key={link.href}><Link href={link.href}>{link.title}</Link></li>
              ))}
            </ul>
          </nav>
        </header>

        <div>
          {children}
        </div>

        <footer className="px-2 py-4 bg-rose-950 text-amber-50 grid grid-cols-3">
          <div className="col-start-2 justify-self-center place-self-end text-center">
            <p>Kodehode</p>
            <p>Jobloop</p>
          </div>
          <a className="col-start-3 justify-self-center hover:scale-105" href={process.env.NEXT_PUBLIC_REPO_ADDRESS} referrerPolicy="no-referrer" target="_blank"><FaGithubSquare size={50}/></a>
        </footer>
        </body>
    </html>
  );
}
